//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms {
    
    
    public partial class XmlElementSignatureInfo {
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WebForms.XmlElementSignature PreviousPage {
            get {
                return ((WebForms.XmlElementSignature)(base.PreviousPage));
            }
        }
    }
}
